[tool]
name = "fastapi-init-project"

version = "0.2.2"
description = "A toolkit for kickstarting FastAPI projects with best practices."
authors = "rameshkannanyt0078@gmail.com"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/rameshkannanyt/fastapi-init"
repository = "https://github.com/rameshkannanyt/fastapi-init"
keywords = ["fastapi", "toolkit", "scaffolding", "development", "fastapi-init"]

[dependencies]
fastapi = "^0.100.0"
uvicorn = "^0.18.0"

[dev-dependencies]
pytest = "^7.0.0"
httpx = "^0.23.0"
black = "^22.0.0"
isort = "^5.10.0"
mypy = "^0.910"